
project_id = "ywydttwbyudpmoxdohbh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[functions.register-accident-report]
verify_jwt = false

[functions.send-official-report-confirmation]
verify_jwt = false

[functions.lookup-vehicle]
verify_jwt = false

[functions.lookup-fni]
verify_jwt = false

[functions.lookup-fva]
verify_jwt = false

[functions.lookup-insurance]
verify_jwt = false

[functions.geocode-location]
verify_jwt = false
