
project_id = "ywydttwbyudpmoxdohbh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[functions]
[functions.register-accident-report]
verify_jwt = true
[functions.send-official-report-confirmation]
verify_jwt = true

[db]
port = 54322
shadow_port = 54320
major_version = 15
