
# Netlify configuration for constalib.fr

[build]
  command = "npm run build"
  publish = "dist"

# Handle client-side routing with React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom domain configuration
[build.environment]
  NODE_VERSION = "18"

# Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
