// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywydttwbyudpmoxdohbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3eWR0dHdieXVkcG1veGRvaGJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NjU0MjgsImV4cCI6MjA1NzU0MTQyOH0.b65oFXCLb5AMvMVbfF4ddZUO-IUydUVUiUpMoAqqLS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);